### PR TITLE
Boot.bat Modifications

### PR DESCRIPTION
**Pull request by OnorioCatenacci**
I modified the boot.bat to correct a long standing issue on Windows. When you get the directory for Erlang it's "\Program Files\erl<erts-version>" by default.  In my case it's \program files\erl7.1.  But when you attempt to call stuff within the batch file, it balks because of the space in "program files".  There are two things that can be done to resolve this.  

1.) Surround everything with quotes.

2.) Get the DOS 8.3 format of the names.

I've modified boot.bat to get the DOS 8.3 version of the names.  From my preliminary testing it looks like that was a big part of the problem.  I don't think all of the windows issues are fixed just yet but I think this is a big step forward.

### CODE REVIEW

**Comment by bitwalker** [comment]
Awesome! Could you squash your commits and I'll merge? Thanks for all the work Onorio!

**Comment by OnorioCatenacci** [comment]
I will do so but I may not get it till Monday.

**Comment by bitwalker** [comment]
No worries! Since we're still WIP until the service part works, there isn't an immediate rush to get it merged into master, but once it's ready to go, I'll get it in there ASAP!

**Comment by OnorioCatenacci** [comment]
Actually got some time to do this tonight.  No rush about integrating it though.

**Comment by OnorioCatenacci** [comment]
This commit should fix several of the main issues with exrm on windows:

1.) Using 8.3 names as noted above will resolve issues with not finding directories correctly.

2.) Modifying the environment variable to name the erlang machine to be started by the Windows service should resolve the issue of the service not being able to start correctly.

3.) Modifying boot_shim.bat to check for admin permissions will prevent users from running the batch files without the correct permissions.

**Comment by OnorioCatenacci** [comment]
Closing the pull request since I'll reapply the changes in a way that will make them less work for both of us.

**Pull request closed without merging**
