### PR TITLE
Cross assemble releases

### PR DESCRIPTION
**Pull request by lexmag**
- Updates relx script to the v1.1.0 [Stable Wombat](https://github.com/erlware/relx/releases/tag/v1.1.0)
- Makes possible to cross assemble releases; requires `system_libs` entry in the config.

### CODE REVIEW

**Comment by bitwalker** [comment]
This is excellent. Thank you!

**Comment by lexmag** [comment]
Thank you, could you release hex package with these changes?

**Comment by bitwalker** [comment]
No problem, it's been released as 0.15.0

**Comment by ajmurmann** [comment]
Being totally new to all things Elixir, can someone point me at some resources to understand how to use this?

**Comment by bitwalker** [comment]
@ajmurmann It's relatively simple, though I haven't experimented with this myself, and I'll add something to the README about this, but you do the following:

1. Make sure you have the cross-compiled Erlang build available on your machine
2. Add `{include_erts, "/path/to/alternate/erlang"}.` to your relx.config if you plan to include Erlang in your release (this is the default behavior, you'll want to do this, or use `{include_erts, false}` if you want the release to use the Erlang installed on the server).
3. Add `{system_libs, "/path/to/alternate/erlang/lib"}.` in your relx.config. This tells exrm to use the Erlang libs from the path to your cross-compiled Erlang build, rather than the default system libs present in your local Erlang installation.

The run `mix release` and you should be good to go. Let me know if this doesn't work for you and I'll revise the instructions with whatever steps are missing or incorrect.

**Comment by lexmag** [comment]
@ajmurmann sorry for being late, @bitwalker's instruction is correct, that's what I'm using for my deployment process.

**Pull request merged**
