### PR TITLE
Win support

### PR DESCRIPTION
**Pull request by OnorioCatenacci**
1.) boot_shim.bat:
    a.) Added special environment variable to allow simple echoing of
    execution for tracing purposes

    b.) Added checking to insure that the user has admin permissions
    before they're allowed to proceed with anything else.

2.) boot.bat

    a.) As above added special environment variable to allow simple
    echoing of execution for tracing purposes.

    b.) Modified the code in several places to use 8.3 form of directory
    names so the batch file doesn't have to rely on the error prone
    technique of surrounding things with double quotes.

    c.) Changed the code in the install subroutine because the machine
    parameter of the erlsrv command was not getting set correctly.

    d.) Modified the code on the attach command because what was there
    before simply didn't execute. This will require more investigation but
    I don't want to hold back these changes until I can investigate
    further.

### CODE REVIEW

**Comment by bitwalker** [comment]
@OnorioCatenacci Hey Onorio, sorry for the delay, could you do the following for me:

- Create a new branch off of master, and check it out (i.e. `git checkout -b win-support`)
- Use `git cherry-pick <commit hash>` to pick your commits on to the new branch
- Close this PR and reopen it using the new branch

I don't want to merge this as is because it is a mix of your commits and mine from master, but I *do* want to merge your changes.

**Comment by OnorioCatenacci** [comment]
Got it. I'll have it done in a little while Paul.

On Fri, Jan 22, 2016 at 12:50 PM, Paul Schoenfelder <
notifications@github.com> wrote:

> @OnorioCatenacci <https://github.com/OnorioCatenacci> Hey Onorio, sorry
> for the delay, could you do the following for me:
>
>    - Create a new branch off of master, and check it out (i.e. git
>    checkout -b win-support)
>    - Use git cherry-pick <commit hash> to pick your commits on to the new
>    branch
>    - Close this PR and reopen it using the new branch
>
> I don't want to merge this as is because it is a mix of your commits and
> mine from master, but I *do* want to merge your changes.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitwalker/exrm/pull/266#issuecomment-173991033>.
>



-- 
Onorio Catenacci

http://onor.io
http://www.google.com/+OnorioCatenacci

**Comment by OnorioCatenacci** [comment]
It's done Paul.  Take a look when you can.

--
Onorio


On Fri, Jan 22, 2016 at 12:58 PM, Onorio Catenacci <Catenacci@ieee.org>
wrote:

> Got it. I'll have it done in a little while Paul.
>
> On Fri, Jan 22, 2016 at 12:50 PM, Paul Schoenfelder <
> notifications@github.com> wrote:
>
>> @OnorioCatenacci <https://github.com/OnorioCatenacci> Hey Onorio, sorry
>> for the delay, could you do the following for me:
>>
>>    - Create a new branch off of master, and check it out (i.e. git
>>    checkout -b win-support)
>>    - Use git cherry-pick <commit hash> to pick your commits on to the
>>    new branch
>>    - Close this PR and reopen it using the new branch
>>
>> I don't want to merge this as is because it is a mix of your commits and
>> mine from master, but I *do* want to merge your changes.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/bitwalker/exrm/pull/266#issuecomment-173991033>.
>>
>
>
>
> --
> Onorio Catenacci
>
> http://onor.io
> http://www.google.com/+OnorioCatenacci
>
>


-- 
Onorio Catenacci

http://onor.io
http://www.google.com/+OnorioCatenacci

**Comment by bitwalker** [comment]
Merged manually in a187fdc

**Pull request closed without merging**
