### PR TITLE
Gather test fixtures in a single directory

### PR DESCRIPTION
**Pull request by lexmag**

### CODE REVIEW

**Comment by lexmag** [comment]
Ping.

**Comment by lexmag** [comment]
Ping :)

**Comment by lexmag** [comment]
Hey @bitwalker, could you please review this?

**Comment by bitwalker** [comment]
Oh shit, sorry man, meant to do this yesterday.

**Comment by bitwalker** [comment]
Thanks man! This is great

**Comment by lexmag** [comment]
No worries. Thankfully, it didn't require any rebases on master. :smile:

**Pull request merged**
