### PR TITLE
Remove embedded mode from foreground

### PR DESCRIPTION
**Pull request by eproxus**
Emebedded mode causes all modules and libraries be loaded up front, making cross platform releases without a bundled ERTS fail. One example is the crypto application. When starting in embedded mode, the crypto .so library is loaded from the release. If the release was made on a different architecture, crypto fails to start and thus the whole node doesn't start. If embedded mode is not used, crypto is loaded on demand from the ERTS on the host (same as in the console and start targets).

### CODE REVIEW

**Comment by bitwalker** [comment]
@eproxus Did you test upgrades with this? If I understand from the [Erlang release handling docs](http://www.erlang.org/doc/design_principles/release_handling.html), embedded mode is required for those to work properly, amongst other things.

**Comment by eproxus** [comment]
Yeah, it seems that it is required to upgrade the runtime itself (possibly some more information [here](http://www.erlang.org/doc/system_principles/create_target.html#id64497)). [LYSE doesn't mention it though](http://learnyousomeerlang.com/relups), which is strange.

**Comment by bitwalker** [comment]
We could perhaps make this a configurable option in exrm, such that embedded mode is used by default, but if you don't intend to do upgrades, and want to be able to deploy a release without building on the target architecture, then you could set a flag to disable embedded mode. I feel like the best practice is to build on your target platform, but I can understand if that's not always the ideal option for everyone.

**Comment by eproxus** [comment]
Yeah, I'm not really sure about this anymore. I'll close this pull request for now, and play around with this a bit more, if that's okay with you.

**Comment by bitwalker** [comment]
Sounds good, just let me know if you need me to take a look at anything!

**Pull request closed without merging**
