### PR TITLE
Use release sys.config when building with conform

### LINKED ISSUE #278: config.exs changes are ignored after the first deploy if you are using conform
Specifically when you are using conform, the conform `.conf` is merged into the `running-config/sys.config` and the new release's `sys.config` appears to be completely ignored.

Related to #194 

To repro:

1. Build a release that uses conform.
2. Deploy and start it, ensure you have a `running-config/sys.config`
3. Make a change to your `config.exs`
4. Build a new release.
5. Deploy the release and do a stop/start.
6. Observe that `running-config/sys.config` does not have your changes and neither does the running environment.

Changes to the `.conf` will get picked up, but not `sys.config` (config.exs)

### PR DESCRIPTION
**Pull request by aaronjensen**
Fixes #278

### CODE REVIEW

**Comment by bitwalker** [comment]
Thanks man, sorry for the delay!

**Comment by aaronjensen** [comment]
No problem, are you planning on cutting a new release soon? Thanks!

**Comment by bitwalker** [comment]
@aaronjensen The most recent release has this commit, and another one is coming shortly to deal with the erlware_commons compile warning.

**Comment by aaronjensen** [comment]
@bitwalker thanks, but unfortunately the latest release is completely broken for us. We'll see if we can figure out why, but at first glance it is not pulling in our conform config file

**Pull request merged**
