### PR TITLE
configurable config_path

### PR DESCRIPTION
**Pull request by umatomba**
add possibility to change default config path using system environments, ref. #124

### CODE REVIEW

**Comment by bitwalker** [comment]
It's important that we keep the dependency on conform locked to a specific version, one can always override it if necessary in their project's mix.exs. Other than that, looks good, I'll do some testing ASAP.

**Comment by umatomba** [comment]
Hi @bitwalker, i have a question. 
Now, in this pull request i have the version with release name in the environment for the config dir. If release name is f.e. 'my_release', it will be $MY_RELEASE_CONFIG_DIR.
Now in production we have other version, with config file variable $CONFIG_FILE, (without release name. With CONFIG_FILE variable is possible to move conform config file location). Now i see two ways:
1) to have $CONFIG_DIR and $CONFIG_FILE (without release name)
2) to have $MY_RELEASE_CONFIG_DIR and $MY_RELEASE_CONFIG_FILE

This future is important for us, because we are using systemd and in service files we redefine environment for current release, example:

```
[Unit]
Description=MyRelease API

[Service]
Environment="HOME=/tmp"
Environment="USER_CONFIG_FILE=/etc/myapps/api-my_release.conf"
Environment="MUTABLE_DIR=/run/api-my_release"
ExecStart=/opt/myapps/api-my_release/1.1.1/bin/my_release foreground
ExecStop=/opt/myapps/api-my_release/1.1.1/bin/my_release stop
```

What do you think is better, 1 or 2?

**Comment by bitwalker** [comment]
@umatomba I prefer 1 if I understand you correctly, having a reliable environment variable is much nicer in my opinion. I do think we should probably change it from $CONFIG_FILE/DIR to something more unique though, that's a bit generic. Perhaps $CONFORM_CONFIG_FILE/DIR?

**Comment by umatomba** [comment]
@bitwalker RELEASE_CONFIG_FILE/DIR  more unique and more generic?

**Comment by bitwalker** [comment]
@umatomba That should work :)

**Comment by bitwalker** [comment]
Merged manually and released in 0.17.2

**Comment by umatomba** [comment]
the work with  RELEASE_CONFIG_FILE/DIR was not done. i have it locally...

**Comment by bitwalker** [comment]
@umatomba Can you push to your repo if it's done? What is remaining? The last I saw in the PR thread was that you were planning to rename the env variable names, which appeared to be complete..

**Comment by umatomba** [comment]
Hi @bitwalker  change has been pushed to #148

**Comment by bitwalker** [comment]
@umatomba Merged, are there other outstanding changes?

**Pull request closed without merging**
