### PR TITLE
Generate config before running the escript

### PR DESCRIPTION
**Pull request by MSch**
Fixes https://github.com/bitwalker/exrm/issues/286

### CODE REVIEW

**Comment by bitwalker** [comment]
Sorry for the delay! Thanks for the PR!

**Comment by MSch** [comment]
@bitwalker no worries! Thanks for merging! As always, I'd appreciate a release on hex.pm so we're not dependent on GitHub.

**Comment by bitwalker** [comment]
I'll get a new release out today, on the road currently, but should be able to do it later in the evening.

**Comment by MSch** [comment]
Appreciate it!

**Comment by bitwalker** [comment]
@MSch Done!

**Pull request merged**
